on:
  schedule:
    # run every 40th minute of every hour
    - cron:  '0 14 * * 1'
  workflow_dispatch:

jobs:
  archive-channels:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        channel: [apple]
        #, , 
    steps:
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          wget https://github.com/upintheairsheep/yt-dlp/archive/refs/heads/patch-9.zip
          unzip patch-9.zip
          cd yt-dlp-patch-9
          pip install -r requirements.txt
          python3 setup.py install
          pip install internetarchive tubeup==0.0.33 snscrape gallery-dl instaup
          mkdir -p ~/.tubeup          
          playwright install firefox
      - uses: actions/cache@v3
        id: cache
        with:
          path: '~/.tubeup'
          key: ${{ matrix.channel }}

      - name: Download and upload channel videos
        env: 
          IA_EMAIL: ${{ secrets.IA_EMAIL }}
          IA_PASSWORD: ${{ secrets.IA_PASSWORD }}
        run: |
          ia configure --username="$IA_EMAIL" --password="$IA_PASSWORD"
          tubeup --get-comments --debug --use-download-archive https://m.youtube.com/watch?v=q4R1YC15lO8
          tubeup --get-comments --debug --use-download-archive https://m.youtube.com/watch?v=tE06ELPwrH4
          tubeup --get-comments --debug --use-download-archive https://m.youtube.com/watch?v=m5rlTrdF5Cs
          tubeup --get-comments --debug --use-download-archive https://m.youtube.com/watch?v=1Ohd_9S8TzA
          tubeup --get-comments --debug --use-download-archive https://m.youtube.com/watch?v=Akmqe17R-a8
          tubeup --get-comments --debug --use-download-archive https://m.youtube.com/watch?v=pSo8aUiRzlk
          tubeup --get-comments --debug --use-download-archive https://m.youtube.com/watch?v=44-4SPIFB6I
          tubeup --get-comments --debug --use-download-archive https://m.youtube.com/watch?v=7QSfT60LpLw
          tubeup --get-comments --debug --use-download-archive https://m.youtube.com/watch?v=-8Uaf7JN6DM
          tubeup --get-comments --debug --use-download-archive https://m.youtube.com/watch?v=4bX5pyxJ3wA
          tubeup --get-comments --debug --use-download-archive https://m.youtube.com/watch?v=bDs_yD4PqqE
          tubeup --get-comments --debug --use-download-archive https://m.youtube.com/watch?v=2EI5qrRYGhA
          tubeup --get-comments --debug --use-download-archive https://m.youtube.com/watch?v=wqD6XDRhLqI
          tubeup --get-comments --debug --use-download-archive https://m.youtube.com/watch?v=GmpWhfz0QGo
          tubeup --get-comments --debug --use-download-archive https://m.youtube.com/watch?v=ALmsPw_rKfo
          tubeup --get-comments --debug --use-download-archive https://m.youtube.com/watch?v=DxiFrrjemA0
          tubeup --get-comments --debug --use-download-archive https://m.youtube.com/watch?v=IWtNdG9MRy0
          tubeup --get-comments --debug --use-download-archive https://m.youtube.com/watch?v=BHi_Yph3-As
          tubeup --get-comments --debug --use-download-archive https://m.youtube.com/watch?v=OrfBqYzolQo
          tubeup --get-comments --debug --use-download-archive https://m.youtube.com/watch?v=wJT_ZbIjNfI
          tubeup --get-comments --debug --use-download-archive https://m.youtube.com/watch?v=jy56k7j1O5M
          tubeup --get-comments --debug --use-download-archive https://m.youtube.com/watch?v=iGqst60BhT0
          tubeup --get-comments --debug --use-download-archive https://m.youtube.com/watch?v=-ysgYvcPA-o
          tubeup --get-comments --debug --use-download-archive https://m.youtube.com/watch?v=WFJT6uA3E2w
          tubeup --get-comments --debug --use-download-archive https://m.youtube.com/watch?v=NPheOjtbriM
          tubeup --get-comments --debug --use-download-archive https://m.youtube.com/watch?v=Xi5Nj4om-8Q
          tubeup --get-comments --debug --use-download-archive https://m.youtube.com/watch?v=NuoIGteFC20
          tubeup --get-comments --debug --use-download-archive https://m.youtube.com/watch?v=5Ylsfttq56c
          tubeup --get-comments --debug --use-download-archive https://m.youtube.com/watch?v=JT9MfjQWJds
          tubeup --get-comments --debug --use-download-archive https://m.youtube.com/watch?v=6_1NJtLWSWg
          tubeup --get-comments --debug --use-download-archive https://m.youtube.com/watch?v=-iLaxOgcUco
          tubeup --get-comments --debug --use-download-archive https://m.youtube.com/watch?v=u0X7sHY-GZc
          tubeup --get-comments --debug --use-download-archive https://m.youtube.com/watch?v=cM660wTiVJk
          tubeup --get-comments --debug --use-download-archive https://m.youtube.com/watch?v=9gkiy253GG4
          tubeup --get-comments --debug --use-download-archive https://m.youtube.com/watch?v=hmBYHXP5wFI
          tubeup --get-comments --debug --use-download-archive https://m.youtube.com/watch?v=BCR651MS72k
          tubeup --get-comments --debug --use-download-archive https://m.youtube.com/watch?v=_yOKHPCAvMQ
          tubeup --get-comments --debug --use-download-archive https://m.youtube.com/watch?v=SNW5GWCXWew
          tubeup --get-comments --debug --use-download-archive https://m.youtube.com/watch?v=IgUeoickDNQ
          tubeup --get-comments --debug --use-download-archive https://m.youtube.com/watch?v=wufkUAnGX5A
          tubeup --get-comments --debug --use-download-archive https://m.youtube.com/watch?v=AFCYwmUzQ-s
          tubeup --get-comments --debug --use-download-archive https://m.youtube.com/watch?v=f2YkGkD8HQ4
          tubeup --get-comments --debug --use-download-archive https://m.youtube.com/watch?v=gLkTXzUZQ1E
          tubeup --get-comments --debug --use-download-archive https://m.youtube.com/watch?v=19JGOCSMwoY
          tubeup --get-comments --debug --use-download-archive https://m.youtube.com/watch?v=sQExArp1cmw
          tubeup --get-comments --debug --use-download-archive https://m.youtube.com/watch?v=d5Tod-OdrdY
          tubeup --get-comments --debug --use-download-archive https://m.youtube.com/watch?v=aEHv1FlW2h4
          tubeup --get-comments --debug --use-download-archive https://m.youtube.com/watch?v=p8WCN4cX488
          tubeup --get-comments --debug --use-download-archive https://m.youtube.com/watch?v=lANdZvUKvmM
          tubeup --get-comments --debug --use-download-archive https://m.youtube.com/watch?v=be-6anY1RYY
          tubeup --get-comments --debug --use-download-archive https://m.youtube.com/watch?v=e74Isn0hoig&t=100s
          tubeup --get-comments --debug --use-download-archive https://m.youtube.com/watch?v=JV6JLcjVJiA
          tubeup --get-comments --debug --use-download-archive https://m.youtube.com/watch?v=RdXtL7fBQhI
          # mkdir ~/.instaup
          # wget ${{ secrets.instaurl }} > ~/.instaup/themariocrafter.login
          #instaup ${{ matrix.channel }} --login themariocrafter --delete
          # sudo mkdir /home/internetarchive
          # cd /home/internetarchive
          # rclone mkdir internetarchive:dumbfoxfurryarchivetiktok
          # sudo rclone mount internetarchive:dumbfoxfurryarchivetiktok
          # tubeup --get-comments --debug https://www.youtube.com/results?app=desktop&sp=mAEA&search_query=samsung+smart+window+2012
          # tubeup --get-comments "twitch.tv/ninja_muffin99/videos?filter=all"    
          # tubeup --get-comments --debug https://youtube.com/@Gygos3654         
          # tubeup https://www.dropbox.com/s/cfgepq38fzr0foz/MOV_0100.mp4?dl=0 --get-comments
          # tubeup http://download.samygo.tv/Others/hidden/SamyGO-VM.7z https://drive.google.com/file/d/1c8D8-KxsISBVQqRh6AvmM5noNeXqdCtq/view?usp=drivesdk https://drive.google.com/file/d/1S9ue_WIfCnrHr2VTh2RK8NOcO-NJA5tx/view?usp=drivesdk  --metadata=collection:open_source_software --metadata=mediatype:software --debug --get-comments
          # yt-dlp -j --no-warnings -i --flat-playlist "https://youtube.com/@${{ matrix.channel }}"| jq -r ".urls" > result.log    
          # tubeup --get-comments https://youtu.be/qaJUdvtozUM
          #wget  https://pastebin.com/raw/hGmSsW0Y -o result.log     
          #while IFS="" read -r p || [ -n "$p" ]
          #do            
          # if ! tubeup $p --debug --get-comments --use-download-archive || true
          #  then
          #    echo "Failed to archive $p"
          #    continue
          # fi
          #done < result.log
      - name: Get sha1 of .ytdlarchive
        id: sha1
        run: |
          export BRAP=$(cat ~/.tubeup/.ytdlarchive | shasum - | head -c 40)
          echo '::set-output name=sha1::$BRAP'
