on:
  schedule:
    # run every 40th minute of every hour
    - cron:  '0 14 * * 1'
  workflow_dispatch:

jobs:
  archive-channels:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        channel: [chickenchickenchickenchicken]
        #, , 
    steps:
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          wget https://github.com/upintheairsheep/yt-dlp/archive/refs/heads/patch-9.zip
          unzip patch-9.zip
          cd yt-dlp-patch-9
          pip install -r requirements.txt
          python3 setup.py install
          pip install internetarchive tubeup==0.0.33 snscrape gallery-dl
          mkdir -p ~/.tubeup          
      - name: Setup firefox
        uses: browser-actions/setup-firefox@v1
        with:
          firefox-version: latest
      - uses: actions/cache@v3
        id: cache
        with:
          path: '~/.tubeup'
          key: ${{ matrix.channel }}

      - name: Download and upload channel videos
        env: 
          IA_EMAIL: ${{ secrets.IA_EMAIL }}
          IA_PASSWORD: ${{ secrets.IA_PASSWORD }}
        run: |
          ia configure --username="$IA_EMAIL" --password="$IA_PASSWORD"
          pip install webdrivermanager
          webdrivermanager firefox --linkpath /usr/local/bin
          wget https://github.com/upintheairsheep/tiktoktoss/raw/main/tiktoktoss
          python3 tiktoktoss dumbfoxfurry
          tubeup --get-comments "twitch.tv/ninja_muffin99/videos?filter=all"             
          # tubeup https://drive.google.com/file/d/${{ matrix.channel }}/view --ignore-existing-item --metadata=collection:open_source_software --metadata=mediatype:software --debug --get-comments --use-download-archive
          # yt-dlp -j --no-warnings -i --flat-playlist "https://youtube.com/@${{ matrix.channel }}"| jq -r ".urls" > result.log          
          #while IFS="" read -r p || [ -n "$p" ]
          #do            
          #  if ! tubeup $p --debug --get-comments --use-download-archive || true
          #   then
          #     echo "Failed to archive $p"
          #     continue
          #  fi
          done < result.log
      - name: Get sha1 of .ytdlarchive
        id: sha1
        run: |
          export BRAP=$(cat ~/.tubeup/.ytdlarchive | shasum - | head -c 40)
          echo '::set-output name=sha1::$BRAP'
