on:
  schedule:
    # run every 40th minute of every hour
    - cron:  '0 14 * * 1'
  workflow_dispatch:

jobs:
  archive-channels:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        channel: [temecula.memes, samsung, oxygenforensics, magnet.forensics]
        #, , 
      fail-fast: false
    steps:
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          wget https://github.com/upintheairsheep/yt-dlp/archive/refs/heads/patch-9.zip
          unzip patch-9.zip
          cd yt-dlp-patch-9
          pip install -r requirements.txt
          python3 setup.py install
          pip install internetarchive tubeup==0.0.33 snscrape gallery-dl instaup
          mkdir -p ~/.tubeup          
          playwright install firefox
      - uses: actions/cache@v3
        id: cache
        with:
          path: '~/.tubeup'
          key: ${{ matrix.channel }}
          # - name: Debugging with ssh
          #   uses: lhotari/action-upterm@v1

      - name: Download and upload channel videos
        env: 
          IA_EMAIL: ${{ secrets.IA_EMAIL }}
          IA_PASSWORD: ${{ secrets.IA_PASSWORD }}
        run: |
          ia configure --username="$IA_EMAIL" --password="$IA_PASSWORD"
          tubeup --get-comments https://www.youtube.com/watch?v=6BkyRyS9Am0
          tubeup https://m.twitch.tv/hikari_no_yume/videos?filter=all
          tubeup https://m.twitch.tv/phantom_arcade/videos?filter=all
          tubeup https://m.twitch.tv/ninja_muffin99/videos?filter=all
          # mkdir /home/runner/.config/instaloader/
          # echo '${{ secrets.INSTA3 }}' | base64 --decode > /home/runner/.config/instaloader/session-themariocrafter
          # instaloader :stories --login themariocrafter 
          # zip -r stories.zip ":stories" 
          # ia upload instagramstories20230208 stories.zip --retries 100
          mkdir ~/.instaup
          echo '${{ secrets.INSTA3 }}' | base64 --decode > /home/runner/.instaup/themariocrafter.login
          instaup ${{ matrix.channel }} --login themariocrafter --delete
          # sudo mkdir /home/internetarchive
          # cd /home/internetarchive
          # rclone mkdir internetarchive:dumbfoxfurryarchivetiktok
          # sudo rclone mount internetarchive:dumbfoxfurryarchivetiktok
          # tubeup --get-comments --debug https://www.youtube.com/results?app=desktop&sp=mAEA&search_query=samsung+smart+window+2012
          # tubeup --get-comments "twitch.tv/ninja_muffin99/videos?filter=all"    
          #tubeup --get-comments --debug https://youtube.com/@Gygos3654         
          # tubeup https://www.dropbox.com/s/cfgepq38fzr0foz/MOV_0100.mp4?dl=0 --get-comments
          # tubeup http://download.samygo.tv/Others/hidden/SamyGO-VM.7z https://drive.google.com/file/d/1c8D8-KxsISBVQqRh6AvmM5noNeXqdCtq/view?usp=drivesdk https://drive.google.com/file/d/1S9ue_WIfCnrHr2VTh2RK8NOcO-NJA5tx/view?usp=drivesdk  --metadata=collection:open_source_software --metadata=mediatype:software --debug --get-comments
          # yt-dlp -j --no-warnings -i --flat-playlist "https://youtube.com/@${{ matrix.channel }}"| jq -r ".urls" > result.log    
          # tubeup --get-comments https://youtu.be/qaJUdvtozUM
          #wget  https://pastebin.com/raw/hGmSsW0Y -o result.log     
          #while IFS="" read -r p || [ -n "$p" ]
          #do            
          # if ! tubeup $p --debug --get-comments --use-download-archive || true
          #  then
          #    echo "Failed to archive $p"
          #    continue
          # fi
          #done < result.log
      - name: Get sha1 of .ytdlarchive
        id: sha1
        run: |
          export BRAP=$(cat ~/.tubeup/.ytdlarchive | shasum - | head -c 40)
          echo '::set-output name=sha1::$BRAP'
