on:
  schedule:
    # run every 40th minute of every hour
    - cron:  '0 14 * * 1'
  workflow_dispatch:

jobs:
  archive-channels:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        channel: [SamsungglobalLG]
        #, , 
    steps:
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install yt-dlp internetarchive tubeup==0.0.33
          mkdir -p ~/.tubeup
      - uses: actions/cache@v3
        id: cache
        with:
          path: '~/.tubeup'
          key: ${{ matrix.channel }}

      - name: Download and upload channel videos
        env: 
          IA_EMAIL: ${{ secrets.IA_EMAIL }}
          IA_PASSWORD: ${{ secrets.IA_PASSWORD }}
        run: |
          ia configure --username="$IA_EMAIL" --password="$IA_PASSWORD"
          seq 6239 | while read OUTPUT
          do
           let COUNTER++
           printf "[DEBUG] After a loop step COUNTER=%d\n" $COUNTER
           tubeup http://nokiatune.audiodraft.com/entry/$COUNTER --metadata=collection:opensource_audio 
          done
          tubeup --get-comments https://youtube.com/user/BikeTemecula https://youtube.com/user/lionage2002 https://youtube.com/user/peanuttia https://youtube.com/user/cgroom14 https://youtube.com/user/emoie678 https://youtube.com/user/xxxtooemo4youxx https://youtube.com/user/amihpornot
          yt-dlp -j --no-warnings -i --flat-playlist "https://youtube.com/c/${{ matrix.channel }}/channels"| jq -r ".urls" > result.log
          while IFS="" read -r p || [ -n "$p" ]
          do
            tubeup $p --get-comments --use-download-archive || true
          done < result.log
          
      
      - name: Get sha1 of .ytdlarchive
        id: sha1
        run: |
          export BRAP=$(cat ~/.tubeup/.ytdlarchive | shasum - | head -c 40)
          echo '::set-output name=sha1::$BRAP'
