on:
  schedule:
    # run every 40th minute of every hour
    - cron:  '0 14 * * 1'
  workflow_dispatch:

jobs:
  archive-channels:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        channel: [GhE7nFOqwv3wx4iIBn-nko2mdA-yZpF_nOFMkPnWPLISV9nj-h0E60vfwJjRj89g.ATmY9aJxwHLlYtHS, FqWCy5TwrqpJSN0PyURzbw-h8--oDYdHI8q01E25JQGayqIUDxu_l5WfABKs1u8S.mIa9NCARgzJSQ4Rm, gz6R-zeHH3hza18lLrh7pRBrZngjAr_V-f7Yx-ZilDGH8kAWRLfOcP44tlDdTLOj.FsS0x6e4Hlh02uUz, B96_caKuJgosZGV20iJ4cqOfaGnysw3ZOT2WvJNaLmWEHa_xk6xchLgkbbKIkPgl.sMiXsLIpB4p9DK74, o6z2aO7w68MzYIDCX9UBGmuMxMidLTCsqsDz6dwJgwm9J2XzGgCr_ktwbuDPhZed.y2VjbuaL50qRU8FQ, RtkzWC0DEun4e6Zse4U8TCGcT77dXd4LHsh93lMFwRnEaSnn8UOij5skxRjSAXyL.oHH6Bm2yiPaxwCVB, agpdoLY1lJY3TRnPDsWmoupFrEsoDsaoisUey0zo4LSaPgdRueLXMyGtBfxYcw8.WXk5Tvx8bhh-ukfF, XukJm6QzOLaUbnP6Pve-T45qh77Vme6OFKQl8qET_mL4O-sa1d-SZ4RTCWqOjzN9.1ctzg5_xak53bkIu, TxbOXgO3_X3qvXpWIysH0SpsWAamXpjlTKoWwBLmgFRVvpv8b5ay6LCKkXSNurs1.mzw61Kc8oknWwSun, hyJUbDgTD-3XaP-BuSekpY2hGxQwSSqtk0fCqXPTs6sMLTz7fXR6DCxR3xPWMxAW.DRcHnnTJrXCkIFQn, CO7nqAgA3ugKMURphKo6ogbH_Tredsk0D5f7MNGPpE97VWo_QSffgyYERZPItQ.bZPbcT_cYe6Mb-qq, HD-QyVvFlSGm9T87mMhZINYVjg2stc6F_vs9yLgo8YZhUeO-_oBs_eF5aHxTklpJ.lk2FSzt24-_IyoPK, wAJ4tShqlGbLyvYMFo2XMR_4D-vMB8fEIzxf2wmFLapIf7bdhPiKOLiJAGD6ljc.RHYRTXh4yVDLyhwd, G0GVgJ8vEJxraaetOogxNL-6AKRDRJOmSlz6c6bCQMHou3_R6BHeyQ77SU6jNvlS.r-caLhdD6Q6BrRqT, 6T5pCwwE0OKjfPGfZgl-IqgixpBkPn7K1JEnMII2TDvUzE8kyKDZ1dvKfJtvd0HU.jZjYnQ8UFqws60TA, HZq_utJe5A7g3ZYP-j11k4aXaOL0uVwZPgmU7wqhl2i5YGfS__C4LgdwwvysiyGc.KHD_xlU3IjYAC9dD, y_XkVxM8dOVialVf2jBKhdyHNljilF7y5wvoJHZjvuELSvtE0rUsn4jmZZNTw-14.5B9zfpppByLVgbOm, H7okUmX95wRjmmuyAKKUMSuqZqKIo5hmMR1cIRSgGCeW9vHubGM5MtuIDGNGBl83.fjOC9iq-xn345-k1, Sm8FGJpA2q8MTa3j7DlpvV40sYMwjxdV9jd1n9RhUBihL6ShgBvZbs9PL5f47IG5.62-l6j8bUwXq9bxP, Mv0dZosP5Jt2UuaMdzyLEg3cwXcxjua8D__l039XOqNLEW5ABVchD0gI-Y8PWPEp.KKPVXBS0c9jX55bR, 8bhBZOPv1uMZCxTxnuX5eftSQrwaOusLfirrEqMjScbFo93ul9nHt2C7qk6hHv4h.IVKjDnCTcsi_VCrs, ZOwwS-Mt55BEqjTRG_V2Gdlk7Qa1FG93_wVbd7LvUbk9Kcmyr0rKm5fU4DJGlNmR.lTs29HdVCVcSBLbr, WiFbUE54Cexk4VBADtPHDYWTk-T9E1NV91k2rLjcTcRgPjpyFcJHslCElAcrY-Lq.Fqtj7myo84qsih_U, DHeSHWshS5xLG9cppAGBTzt24JqwNPLuxT7LLxmyH3MBj8EUKf8lpAuY7N7leRfM.ZdTyhk4yUntq71XA, v5SviJf2AcwXE2sacGa3kgV1ILIzHo1yhtRfh6kb1DvGk6FoiN7-c-ii4za_Tz-8.ZeUDkEHNXNthy0zY, 7FKRUBaQzGMwc30XnuLMbWJTndWAZ5Ahcg2ERAgfZN1wdV29AVcGrk65Ffj70iZx.lieyqV-IBtjeqeHy, zahgSFVic3OMjD7AfAM5MUtcgLZl1sSYpqpBAkooheD_V653FKRGe2KuGznfl80RTgldlVVafRKaCy5r.sHRGu4Ah4gorjtX4, H06OiMhP4NfyrbKLzhnbwV-toYSH8SqFHZLMm7Cd-uH9WEAH5w4bh0KRxWmOBks.AQ67GZ1ITVrmyUCo]
    
    steps:
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install yt-dlp internetarchive tubeup
          mkdir -p ~/.tubeup

      - uses: actions/cache@v3
        id: cache
        with:
          path: '~/.tubeup'
          key: ${{ matrix.channel }}

      - name: Download and upload channel videos
        env: 
          IA_EMAIL: ${{ secrets.IA_EMAIL }}
          IA_PASSWORD: ${{ secrets.IA_PASSWORD }}
        run: |
          ia configure --username="$IA_EMAIL" --password="$IA_PASSWORD"
          tubeup "https://zoom.us/rec/play/${{ matrix.channel }}" --get-comments --use-download-archive || true
          

      - name: Get sha1 of .ytdlarchive
        id: sha1
        run: |
          export BRAP=$(cat ~/.tubeup/.ytdlarchive | shasum - | head -c 40)
          echo '::set-output name=sha1::$BRAP'
