on:
  schedule:
    # run every 40th minute of every hour
    - cron:  '0 14 * * 1'
  workflow_dispatch:

jobs:
  archive-channels:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        channel: [6JV_c-36-DM3T9GQsASDC_F7W46_J6msgSQZ-vcEn0q9VCVVNlKiNLcaYuNMjek9LoEdvtcD0YiquC00, 75V5IbigrzM3G4fGuASDUPR5W424e66sg3AYq_VfxU21VCQAMFOmZ-cbYeEr7TY5BuJnC7IMb4OwtybM, 65V5deGq-Do3T9bHuASDAv4tW420f_ms1iIb-vIKzEqzUiEFNFWiYONAN-vRvNmKnlg6z95Y4mNQ9QJQ, 6ccrIuigqG83GIaT4wSDAv59W9W5J_-s1HUe_6UPykq3V3hVN1emMucTYLEJiA87rIkEPcGptB0Dp_dH, EtJ1qprNi05i05A7ETJTNMctWXtnj__OTmPVzJ7wfehlQTjSJMf7-0CIjHqjKGjXWyaFdhwy4x3Xylob.GjCnWFG_QVriQA53, 75Usc7j8rjg3E92S4gSDAf95W9S9K6-sg3dP_voImR60WiEHYVSmYrsbNwNE1_6-jwlwLx5cg1IeyjM]
    
    steps:
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install yt-dlp internetarchive tubeup
          mkdir -p ~/.tubeup

      - uses: actions/cache@v3
        id: cache
        with:
          path: '~/.tubeup'
          key: ${{ matrix.channel }}

      - name: Download and upload channel videos
        env: 
          IA_EMAIL: ${{ secrets.IA_EMAIL }}
          IA_PASSWORD: ${{ secrets.IA_PASSWORD }}
        run: |
          ia configure --username="$IA_EMAIL" --password="$IA_PASSWORD"
          tubeup "https://zoom.us/rec/play/${{ matrix.channel }}" --get-comments --use-download-archive || true
          

      - name: Get sha1 of .ytdlarchive
        id: sha1
        run: |
          export BRAP=$(cat ~/.tubeup/.ytdlarchive | shasum - | head -c 40)
          echo '::set-output name=sha1::$BRAP'
