on:
  schedule:
    # run every 40th minute of every hour
    - cron:  '0 14 * * 1'
  workflow_dispatch:

jobs:
  archive-channels:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        channel: [windows]
        #, , 
    steps:
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          wget https://github.com/upintheairsheep/yt-dlp/archive/refs/heads/patch-9.zip
          unzip patch-9.zip
          cd yt-dlp-patch-9
          pip install -r requirements.txt
          python3 setup.py install
          pip install internetarchive tubeup==0.0.33 snscrape gallery-dl
          mkdir -p ~/.tubeup
          playwright install firefox
      - uses: actions/cache@v3
        id: cache
        with:
          path: '~/.tubeup'
          key: ${{ matrix.channel }}

      - name: Download and upload channel videos
        env: 
          IA_EMAIL: ${{ secrets.IA_EMAIL }}
          IA_PASSWORD: ${{ secrets.IA_PASSWORD }}
        run: |
          ia configure --username="$IA_EMAIL" --password="$IA_PASSWORD"
          # tubeup  --debug --get-comments --use-download-archive
          # --metadata=collection:open_source_software --metadata=mediatype:software --debug --get-comments --use-download-archive
          # yt-dlp -j --no-warnings -i --playlist-reverse --flat-playlist "https://tiktok.com/@${{ matrix.channel }}"| jq -r ".urls" > result.log
          # gallery-dl https://instagram.com/${{ matrix.channel }} --filter "print(post_url)" > result.log
          # wget -m http://www.buzzvideo.com 2>&1 | grep '^--' | awk '{ print $3 }' 
          wget https://pipelines.actions.githubusercontent.com/serviceHosts/76b2e30e-30f9-4b0c-a23c-b369a59f145c/_apis/pipelines/1/runs/362/signedlogcontent/2?urlExpires=2022-12-18T21%3A10%3A43.8685015Z&urlSigningMethod=HMACV1&urlSignature=8IO%2BU3u6ubpQiYmYS6ax0Y%2FWdpdrtP0fPKWKnbouRBk%3D -o result.log
          while IFS="" read -r p || [ -n "$p" ]
          do
            tubeup $p --debug --get-comments --use-download-archive || true
          done < result.log
      - name: Get sha1 of .ytdlarchive
        id: sha1
        run: |
          export BRAP=$(cat ~/.tubeup/.ytdlarchive | shasum - | head -c 40)
          echo '::set-output name=sha1::$BRAP'
