on:
  schedule:
    # run every 40th minute of every hour
    - cron:  '0 14 * * 1'
  workflow_dispatch:

jobs:
  archive-channels:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        channel: [windows]
        #, , 
    steps:
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          wget https://github.com/upintheairsheep/yt-dlp/archive/refs/heads/patch-9.zip
          unzip patch-9.zip
          cd yt-dlp-patch-9
          pip install -r requirements.txt
          python3 setup.py install
          pip install internetarchive tubeup==0.0.33 snscrape gallery-dl
          mkdir -p ~/.tubeup
          playwright install firefox
      - uses: actions/cache@v3
        id: cache
        with:
          path: '~/.tubeup'
          key: ${{ matrix.channel }}

      - name: Download and upload channel videos
        env: 
          IA_EMAIL: ${{ secrets.IA_EMAIL }}
          IA_PASSWORD: ${{ secrets.IA_PASSWORD }}
        run: |
          ia configure --username="$IA_EMAIL" --password="$IA_PASSWORD"
          # tubeup https://www.buzzvideo.com/@toshi/%E3%80%90%E7%99%92%E3%81%97%E3%80%91%E3%81%B2%E3%82%87%E3%81%A3%E3%81%93%E3%82%8A%E3%81%AB%E3%82%83%E3%82%93%E3%81%93%E3%80%82%E3%81%8B%E3%82%8F%E3%81%84%E3%81%84%E3%83%8B%E3%83%A3%E3%83%BC-BsKG2_gzU2M?referer=foryou&pid=website_feed --debug --get-comments --use-download-archive
          # --metadata=collection:open_source_software --metadata=mediatype:software --debug --get-comments --use-download-archive
          # yt-dlp -j --no-warnings -i --playlist-reverse --flat-playlist "https://tiktok.com/@${{ matrix.channel }}"| jq -r ".urls" > result.log
          gallery-dl https://instagram.com/${{ matrix.channel }} --filter "print(post_url)" > result.log
          while IFS="" read -r p || [ -n "$p" ]
          do
            tubeup $p --get-comments --use-download-archive || true
          done < result.log
      - name: Get sha1 of .ytdlarchive
        id: sha1
        run: |
          export BRAP=$(cat ~/.tubeup/.ytdlarchive | shasum - | head -c 40)
          echo '::set-output name=sha1::$BRAP'
