on:
  schedule:
    # run every 40th minute of every hour
    - cron:  '0 14 * * 1'
  workflow_dispatch:

jobs:
  archive-channels:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        channel: [windows]
    steps:
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install yt-dlp internetarchive tubeup
          mkdir -p ~/.tubeup

      - uses: actions/cache@v3
        id: cache
        with:
          path: '~/.tubeup'
          key: ${{ matrix.channel }}

      - name: Download and upload channel videos
        env: 
          IA_EMAIL: ${{ secrets.IA_EMAIL }}
          IA_PASSWORD: ${{ secrets.IA_PASSWORD }}
        run: |
          ia configure --username="$IA_EMAIL" --password="$IA_PASSWORD"  
          tubeup https://mobile.twitter.com/CocaCola/status/1542855566648901632 https://pbs.twimg.com/media/FZkyUldWAAEJ13a?format=jpg&name=900x900 https://mobile.twitter.com/harbenie/status/1371291284179095554 https://mobile.twitter.com/SonicFreak94/status/1544176542128824320 https://mobile.twitter.com/Dublicus/status/1546202785061842944 https://mobile.twitter.com/WtfImgvids/status/1471147438979309575 https://mobile.twitter.com/jeb_beanzos/status/1556235722935242752 https://mobile.twitter.com/Ender_Bot/status/1556199193902862336 https://pbs.twimg.com/media/Ewe9sRiUcAAVUbT?format=jpg&name=900x900
          yt-dlp -j --no-warnings --flat-playlist "https://instagram.com/${{ matrix.channel }}" | jq -r ".urls" > result.log
          while IFS="" read -r p || [ -n "$p" ]
          do
            tubeup $p --get-comments --use-download-archive || true
          done < result.log

      - name: Get sha1 of .ytdlarchive
        id: sha1
        run: |
          export BRAP=$(cat ~/.tubeup/.ytdlarchive | shasum - | head -c 40)
          echo '::set-output name=sha1::$BRAP'
