on:
  schedule:
    # run every 40th minute of every hour
    - cron:  '0 14 * * 1'
  workflow_dispatch:

jobs:
  archive-channels:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        channel: [UCpT46G77geEsEUOKzb49enQ, UC45TEIruqmhSHDkV8Mnn9Gw, UCBdCaezoJipdjufwKz-l2ZA, UCevKzawKjk-GDsAfe5ctIvQ, UCy6FQPAddTADou_GgwuY40A, UCleVUgeqcJcZzde-dZ90Gpg, UCZHLcqD05W23Prk-FHjsRLA, UC0MIRvnA9q7X1xluGFvyt2g, UCbvhpSoR3TQobIbIM9euZcQ, UCgAIPOyi1TjGzN3gfVbJ1cg, UCPoSYir-KCtAuybN-zsvoXg, UCR2vIHxqKXXD90UIilBfpGA, UCm4ukk3Su3p62cI5QmFpeZQ, UC1Yq1vShuN1ft0myXFchcsQ, UC0v-GoU_xhZ1sWj2iJ7YUrw, UCZvXEPVQaKdVYZDAK7IUvBg]
    
    steps:
      - uses: actions/setup-python@v2

      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: '3.10.1'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install yt-dlp internetarchive tubeup

      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%S-%M-%H_%Y-%m-%d')"

      - uses: actions/cache@v2
        id: cache
        with:
          path: ~/.tubeup/.ytdlarchive
          key: ${{ matrix.channel }}-d${{ steps.date.outputs.date }}
          restore-keys: ${{ matrix.channel }}-d

      - name: Download and upload channel videos
        env: 
          IA_EMAIL: ${{ secrets.IA_EMAIL }}
          IA_PASSWORD: ${{ secrets.IA_PASSWORD }}
        run: |
          ia configure --username="$IA_EMAIL" --password="$IA_PASSWORD"
          yt-dlp -j --no-warnings --flat-playlist "https://youtube.com/channel/${{ matrix.channel }}" | jq -r ".urls" > result.log
          while IFS="" read -r p || [ -n "$p" ]
          do
            tubeup $p || true
          done < result.log
          
