on:
  schedule:
    # run every 40th minute of every hour
    - cron:  '0 14 * * 1'
  workflow_dispatch:

jobs:
  archive-channels:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        channel: [1VP9Ru2jjMgkPL_48mkzyq64Wce3aztQf, 1HECLx_mySMOhfrNEqOFXQFP0rWvYvvj1, 1fHJDLFzOE-R1FV-I-Kw2ehwaYwyy0nbT, 18_Y_bKhwxrvAJ4AnK7h2ZGgK8oyzTCw7, 1Trgf2algnIrQ94ldZfdtDn0sVV4EfZQk, 1MaG8S3tL98_KkO5s8y58LF5a2MJnv2P4, 1HguWU6kxrzcHpTbQRkdFZcoESTj3bFg4]
    
    steps:
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install yt-dlp internetarchive tubeup
          mkdir -p ~/.tubeup

      - uses: actions/cache@v3
        id: cache
        with:
          path: '~/.tubeup'
          key: ${{ matrix.channel }}

      - name: Download and upload channel videos
        env: 
          IA_EMAIL: ${{ secrets.IA_EMAIL }}
          IA_PASSWORD: ${{ secrets.IA_PASSWORD }}
        run: |
          ia configure --username="$IA_EMAIL" --password="$IA_PASSWORD"
          tubeup "https://drive.google.com/file/d/${{ matrix.channel }}" --get-comments --use-download-archive || true
          

      - name: Get sha1 of .ytdlarchive
        id: sha1
        run: |
          export BRAP=$(cat ~/.tubeup/.ytdlarchive | shasum - | head -c 40)
          echo '::set-output name=sha1::$BRAP'
